csv:
  input_directory_history: csv_reservations_history
  input_directory_onhand: csv_reservations_onhand
  input_directory_customer: csv_customer
  output_directory: processed-csv
  encoding: Shift_JIS

path:
  download_path: C:\Users\kifunosato\Downloads
  driver_path: C:\Users\kifunosato\Desktop\program\chromedriver-win32\chromedriver.exe

setting:
  message:
    success: false
    error: true

  history:
    manual_date: false
    manual_start_date: 2019-01-01
    manual_end_date: 2025-06-15
    manual_time_sleep: 300
    selenium: true
    import: false
  
  onhand:
    manual_date: false
    manual_start_date: 2022-03-01
    manual_end_date: 2025-02-22
    manual_time_sleep: 180
    selenium: true
    import: false

  customer:
    selenium: true
    import: false

